window.NX_SCREENS=window.NX_SCREENS||{};window.NX_SCREENS["sensors"]=`<section class="screen" data-title="Sensor Modules" id="sensors">
<div class="screen-intro"><div><div class="overline">MEASUREMENT &amp; SENSOR MODULES</div><h1>Los módulos no son silos. Alimentan el mismo cerebro analítico.</h1><p>La empresa activa las capacidades que necesita y sus resultados pueden convertirse en nuevas dimensiones de análisis.</p></div><span class="pill-soft">Modular architecture</span></div>
<div class="sensor-grid">
<article class="sensor-card core"><div class="sensor-top"><span class="sensor-icon">◌</span><span class="tag blue">Core MVP</span></div><h3>Continuous Climate</h3><p>Muestreo continuo, dimensiones, tendencias, preguntas rotativas y pulses activados por señales.</p><div class="sensor-output">Output <b>Workload · Support · Intent to Stay</b></div></article>
<article class="sensor-card core"><div class="sensor-top"><span class="sensor-icon">↘</span><span class="tag blue">Core MVP</span></div><h3>Turnover &amp; Retention</h3><p>Cohortes, survival analysis, permanencia y posibles leading indicators.</p><div class="sensor-output">Output <b>7/30/60/90/180d · risk patterns</b></div></article>
<article class="sensor-card"><div class="sensor-top"><span class="sensor-icon">∿</span><span class="tag green">Sensor</span></div><h3>Absence Intelligence</h3><p>Frecuencia, recurrencia, duración, turnos y relaciones temporales.</p><div class="sensor-output">Output <b>absence frequency · recurrence</b></div></article>
<article class="sensor-card"><div class="sensor-top"><span class="sensor-icon">360</span><span class="tag green">Sensor</span></div><h3>360° Leadership</h3><p>Brechas self vs. others y conexión con señales del equipo.</p><div class="sensor-output">Output <b>leadership dimensions · gaps</b></div></article>
<article class="sensor-card"><div class="sensor-top"><span class="sensor-icon">MX</span><span class="tag amber">Framework</span></div><h3>NOM-035</h3><p>Aplicación metodológica específica y lectura agregada cuando corresponda.</p><div class="sensor-output">Output <b>psychosocial risk factors</b></div></article>
<article class="sensor-card"><div class="sensor-top"><span class="sensor-icon">→</span><span class="tag green">Sensor</span></div><h3>Onboarding Intelligence</h3><p>Experiencia inicial, retención temprana, manager y training.</p><div class="sensor-output">Output <b>early-stage friction · cohorts</b></div></article>
<article class="sensor-card"><div class="sensor-top"><span class="sensor-icon">↗</span><span class="tag green">Sensor</span></div><h3>Training Impact</h3><p>Baseline, post, aplicación y seguimiento longitudinal.</p><div class="sensor-output">Output <b>knowledge · transfer · behavior</b></div></article>
<article class="sensor-card"><div class="sensor-top"><span class="sensor-icon">↪</span><span class="tag green">Sensor</span></div><h3>Exit Intelligence</h3><p>Razones de salida contextualizadas con historia y segmentos.</p><div class="sensor-output">Output <b>exit reasons · recurring patterns</b></div></article>
<article class="sensor-card optional"><div class="sensor-top"><span class="sensor-icon">+</span><span class="tag gray">Optional</span></div><h3>Business KPIs</h3><p>Productividad, calidad, seguridad, ventas u otras variables operativas.</p><div class="sensor-output">Output <b>business context</b></div></article>
</div>
<article class="panel utility-banner"><div><div class="overline">UTILITY · NO CORE</div><h2>¿Excel sucio? También lo podemos resolver.</h2><p>Data Cleaner y estandarización son utilidades opcionales. Un cliente con datos limpios puede utilizar todo el producto sin tocar esta capa.</p></div><div class="utility-actions"><span>CSV / XLSX</span><span>Dates</span><span>Duplicates</span><span>Categories</span></div></article>
</section>`;
